// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyA0ry9IO9ZvuJ3pUB8L_VITfmSHhCGvDag',
//     appId: '1:861268172960:web:5c4df0670149ab2b6ce9c5',
//     messagingSenderId: '861268172960',
//     projectId: 'ecommarce-89aed',
//     authDomain: 'ecommarce-89aed.firebaseapp.com',
//     storageBucket: 'ecommarce-89aed.appspot.com',
//     measurementId: 'G-BJZX9FSWKD',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBOppU16FW04iDNWrjFkwlmBNC-gh7ACUE',
//     appId: '1:861268172960:android:3b2127d0fa4ba2776ce9c5',
//     messagingSenderId: '861268172960',
//     projectId: 'ecommarce-89aed',
//     storageBucket: 'ecommarce-89aed.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAAgEg3fq1Sw070GznkuuOYV48jyVhtYeE',
//     appId: '1:861268172960:ios:b00ace2e4c2d55646ce9c5',
//     messagingSenderId: '861268172960',
//     projectId: 'ecommarce-89aed',
//     storageBucket: 'ecommarce-89aed.appspot.com',
//     iosBundleId: 'com.example.commarceProject',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAAgEg3fq1Sw070GznkuuOYV48jyVhtYeE',
//     appId: '1:861268172960:ios:b00ace2e4c2d55646ce9c5',
//     messagingSenderId: '861268172960',
//     projectId: 'ecommarce-89aed',
//     storageBucket: 'ecommarce-89aed.appspot.com',
//     iosBundleId: 'com.example.commarceProject',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyA0ry9IO9ZvuJ3pUB8L_VITfmSHhCGvDag',
//     appId: '1:861268172960:web:0fc8e7a7e24f79c56ce9c5',
//     messagingSenderId: '861268172960',
//     projectId: 'ecommarce-89aed',
//     authDomain: 'ecommarce-89aed.firebaseapp.com',
//     storageBucket: 'ecommarce-89aed.appspot.com',
//     measurementId: 'G-2F6QGEHDCT',
//   );
// }
